name: Release Patch on Flix Nightly

on: workflow_dispatch

jobs:
  release-nightly:
    runs-on: ubuntu-latest
    steps:
      - name: Check out main branch
        uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v2.5.0
        with:
          java-version: 21
          distribution: zulu
      - name: Download Flix JAR
        run: |
          url="https://flix.dev/nightly/flix-latest.jar"
          curl -L -f "$url" > flix.jar
      - name: Run tests
        run: |
          java -jar flix.jar test --github-token ${{ github.token }}
      - name: Build the package
        run: |
          java -jar flix.jar build-pkg
      - name: Release the package
        run: |
          java -jar flix.jar release --yes